connection: "telemetry"
label: "Mozilla VPN"
include: "//looker-hub/mozilla_vpn/explores/*"
include: "//looker-hub/mozilla_vpn/dashboards/*"
include: "views/*"
include: "explores/*"
include: "dashboards/*"