connection: "telemetry"
label: "Operational Monitoring"
include: "//looker-hub/operational_monitoring/explores/*"
include: "//looker-hub/operational_monitoring/dashboards/*"
include: "views/*"
include: "explores/*"
include: "dashboards/opmon-preview.dashboard"
