connection: "telemetry"
label: "mozregression"
include: "//looker-hub/mozregression/explores/*"
include: "//looker-hub/mozregression/dashboards/*"
include: "views/*"
include: "explores/*"
include: "dashboards/*"
