connection: "telemetry"
label: "Firefox Klar for iOS"
include: "//looker-hub/klar_ios/explores/*"
# include: "//looker-hub/klar_ios/dashboards/*"
# include: "views/*"
# include: "explores/*"
# include: "dashboards/*"
