connection: "telemetry"
label: "Mozilla Developer Network"
include: "//looker-hub/mdn_yari/explores/*"
include: "//looker-hub/mdn_yari/dashboards/*"
include: "views/*"
include: "explores/*"
include: "dashboards/*"