connection: "telemetry"
label: "Mozilla Developer Network"
include: "//looker-hub/mdn_yari/explores/action.explore.lkml"
include: "//looker-hub/mdn_yari/explores/deletion_request.explore.lkml"
include: "explores/*"
