connection: "telemetry"
label: "Monitoring (Data Pipeline)"
include: "//looker-hub/monitoring/explores/*"
include: "//looker-hub/monitoring/dashboards/*"
include: "views/*"
include: "explores/*"
include: "dashboards/*"