connection: "telemetry"
label: "Firefox Accounts Backend"
include: "//looker-hub/accounts_backend/explores/*"
include: "//looker-hub/accounts_backend/dashboards/*"
include: "views/*"
include: "explores/*"
include: "dashboards/*"