connection: "telemetry"
label: "Firefox Focus for Android"
include: "//looker-hub/focus_android/explores/*"
# include: "//looker-hub/focus_android/dashboards/*"
# include: "views/*"
# include: "explores/*"
# include: "dashboards/*"
