connection: "telemetry"
label: "Firefox for Desktop"
include: "//looker-hub/firefox_desktop/explores/*"
include: "//looker-hub/firefox_desktop/dashboards/*"
include: "views/*"
include: "explores/*"
include: "dashboards/*"