connection: "telemetry"
label: "Viu Politica"
include: "//looker-hub/viu_politica/explores/*"
include: "//looker-hub/viu_politica/dashboards/*"
include: "views/*"
include: "explores/*"
include: "dashboards/*"