connection: "telemetry"
label: "Awesome Bar"
include: "//looker-hub/awesome_bar/explores/*"
include: "//looker-hub/awesome_bar/dashboards/*"
include: "views/*"
include: "explores/*"
include: "dashboards/*"