connection: "telemetry"
label: "mozphab"
include: "//looker-hub/mozphab/explores/*"
# include: "//looker-hub/mozphab/dashboards/*"
# include: "views/*"
# include: "explores/*"
# include: "dashboards/*"
