connection: "bigquery-oauth"
label: "Contextual Services"
include: "//looker-hub/contextual_services/explores/*"
include: "//looker-hub/contextual_services/dashboards/*"
include: "views/*"
include: "explores/*"
include: "dashboards/*"