connection: "telemetry"
label: "Combined Browser Metrics"
include: "views/active_users_aggregates.view"
include: "views/active_users_aggregates_device.view"
include: "views/cohort_daily_statistics.view"
include: "views/use_counters.view"
include: "explores/active_users_aggregates.explore"
include: "explores/active_users_aggregates_device.explore"
include: "explores/user_retention.explore"
include: "explores/use_counters.explore"
