connection: "telemetry"
label: "Subscription Platform"
include: "//looker-hub/subscription_platform/explores/*"
#include: "//looker-hub/subscription_platform/dashboards/*"
include: "views/*"
include: "explores/*"
#include: "dashboards/*"
