connection: "telemetry"
label: "Subscription Platform"
include: "//looker-hub/subscription_platform/explores/*"
#include: "//looker-hub/subscription_platform/dashboards/*"
include: "explores/active_subscriptions.explore.lkml"
include: "explores/daily_active_logical_subscriptions.explore.lkml"
include: "explores/daily_multi_service_customers.explore.lkml"
include: "explores/logical_subscription_events.explore.lkml"
include: "explores/logical_subscriptions.explore.lkml"
include: "explores/monthly_active_logical_subscriptions.explore.lkml"
include: "explores/stripe_subscriptions.explore.lkml"
include: "dashboards/*"
